security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ORGANISATEUR: ROLE_USER
        ROLE_ADMIN:        [ROLE_ORGANISATEUR, ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/login,    roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/evenements/nouveau,   roles: ROLE_USER }
        - { path: ^/evenements/.*/modifier,  roles: ROLE_USER }
        - { path: ^/evenements/.*/supprimer, roles: ROLE_USER }
        - { path: ^/evenements/.*/inscription, roles: ROLE_USER }
        - { path: ^/lieux/nouveau, roles: ROLE_ADMIN }
        - { path: ^/tags,     roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10